<div class="page-header">
    <h2>Додати освіту шукача роботи</h2>
</div>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <form method="post" class="form-horizontal">
            <fieldset>
                <div class="form-group">
                    <label class="col-sm-4 control-label">Навчальний заклад:</label>
                    <div class="col-sm-8">
                        <input type="text" name="school" class="form-control" tabindex="1" autofocus placeholder="Назва навчального закладу" value="<?=$form->school?>">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-4 control-label">Спеціальність:</label>
                    <div class="col-sm-8">
                        <input type="text" name="specialty" class="form-control" tabindex="2" placeholder="Назва спеціальності" value="<?=$form->specialty?>">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-4 control-label">Рівень освіти:</label>
                    <div class="col-sm-8">
                        <input type="text" name="level_school" class="form-control" tabindex="3" placeholder="Вища, незакінчена вище, середня" value="<?=$form->level_school?>">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-4 control-label">Дата закінчення:</label>
                    <div class="col-sm-8">
                        <input type="date" name="freedate" class="form-control" tabindex="4" value="<?=$form->freedate?>">
                    </div>
                </div>

            </fieldset>
            <br>
            <p>
                <button class="btn btn-success btn-lg" type="submit"><i class="fa fa-plus-circle" aria-hidden="true"></i> Додати освіту</button>
                <a href="/showjobsearch/<?=$form->id_jobseekers?>#edu" class="btn btn-danger btn-lg" role="button"><i class="fa fa-ban" aria-hidden="true"></i> Відмінити</a>
            </p>
        </form>
    </div>
</div>


<b id="flash"><?=\Library\Session::getFlash()?></b>
