<div class="page-header">
    <h2>Додати освіту шукача роботи</h2>
</div>
<form method="post">
    <fieldset>
        <label>Навчальний заклад:
            <input type="text" name="school" value="<?=$form->school?>">
        </label><br>
        <label>Спеціальність:
            <input type="text" name="specialty" value="<?=$form->specialty?>">
        </label><br>
        <label> Рівень освіти:
            <input type="text" name="level_school" value="<?=$form->level_school?>">
        </label><br>
                <label> Дата закінчення:
            <input type="date" name="freedate" value="<?=$form->freedate?>">
        </label><br>

    </fieldset>
    <button class="btn btn-success btn-lg" type="submit"><i class="fa fa-plus-circle" aria-hidden="true"></i> Додати освіту</button>
    <a href="/showjobsearch/<?=$form->id_jobseekers?>" class="btn btn-danger btn-lg" role="button"><i class="fa fa-ban" aria-hidden="true"></i> Відмінити</a>
</form>

<b id="flash"><?=\Library\Session::getFlash()?></b>
