<h2 class="fontColorHeader">Вас вітає Програма працевлаштування осіб з інвалідністю та інших верств населення -
    <?=$user['region']?></h2>
<h2>
    
</h2>
<h3>Керівник та відповідальна особа: <b><?=$user['surname']?>  <?=$user['username']?> <?=$user['father']?></b><br>
    Початок роботи Програми: <b>2016 рік</b>
</h3>

<img src="img/01.png" />

<br><br>
<a href="/thirdpage" class="btn btn-primary" role="button">Перейти до бази даних</a>




