<div class="page-header">
    <h2>Додати роботу що шукає</h2>
</div>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <form method="post" class="form-horizontal">
            <fieldset>
                <div class="form-group">
                    <label class="col-sm-4 control-label">Спеціальність:</label>
                    <div class="col-sm-8">
                        <input type="text" name="specialty" class="form-control" tabindex="1" autofocus value="<?=$form->specialty?>">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-4 control-label">Графік роботи:</label>
                    <div class="col-sm-8">
                        <select name="job_grapf" class="form-control" tabindex="2">
                            <option value="1">
                                Повний робочий день
                            </option>
                            <option value="2">
                                Скорочений робочий день
                            </option>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-4 control-label">Тип роботи:</label>
                    <div class="col-sm-8">
                        <select name="sort_job" class="form-control" tabindex="3">
                            <option value="1">
                                Основна
                            </option>
                            <option value="2">
                                Сумісництво
                            </option>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-4 control-label">Заробітня плата:</label>
                    <div class="col-sm-8">
                        <div class="input-group">
                            <input type="text" name="salary" class="form-control"  tabindex="4" placeholder="Очикуваний рівень заробітньої платні" value="<?=$form->salary?>">
                            <div class="input-group-addon">грн.</div>
                        </div>
                    </div>
                </div>

            </fieldset>

        <p>
            <button class="btn btn-success btn-lg" type="submit"><i class="fa fa-plus-circle" aria-hidden="true"></i> Додати роботу</button>
            <a href="/showjobsearch/<?=$form->id_jobseekers?>#serc" class="btn btn-danger btn-lg" role="button"><i class="fa fa-ban" aria-hidden="true"></i> Відмінити</a>
        </p>
        </form>
    </div>
</div>

<b id="flash"><?=\Library\Session::getFlash()?></b>

