<div class="page-header">
    <h2>Додати анкету шукача роботи</h2>
</div>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
    <h4>
        <form method="post"  class="form-horizontal" id="jobseekercreate">
            <fieldset>
                <div class="form-group">
                    <label class="col-sm-4 control-label">Прізвище:</label>
                    <div class="col-sm-8">
                        <input type="text" name="surname" id="surname" class="form-control" placeholder="" tabindex="1" autofocus value="<?=$form->surname?>">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-4 control-label">Ім'я:</label>
                    <div class="col-sm-8">
                        <input type="text" name="jobseekername" id="jobseekername" class="form-control" placeholder="" tabindex="2" value="<?=$form->jobseekername?>">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-4 control-label">По-батькові:</label>
                    <div class="col-sm-8">
                        <input type="text" name="father"  id="father" class="form-control" placeholder="" tabindex="3" value="<?=$form->father?>">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-4 control-label">Стать:</label>
                    <div class="col-sm-8">
                        <select name="stat" class="form-control" tabindex="4" >
                            <option value="male">
                                чоловіча
                            </option>
                            <option value="female">
                                жіноча
                            </option>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-4 control-label">Дата народження:</label>
                    <div class="col-sm-8">
                        <input type="date" class="form-control" name="birthdate" tabindex="5" value="<?=$form->birthdate?>">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-4 control-label">Паспорт:</label>
                    <div class="col-sm-8">
                        <input type="text" class="form-control" name="pasport" placeholder="XX-111111" tabindex="6" value="<?=$form->pasport?>">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-4 control-label">Адреса:</label>
                    <div class="col-sm-8">
                        <input type="text" class="form-control" name="adress" tabindex="7" value="<?=$form->adress?>">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-4 control-label">Номер телефону:</label>
                    <div class="col-sm-8">
                        <div class="input-group">
                            <div class="input-group-addon">+38</div>
                            <input type="text" class="form-control" placeholder="0501234567" name="contact" tabindex="8" value="<?=$form->contact?>">
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-4 control-label">E-mail:</label>
                    <div class="col-sm-8">
                        <input type="email" class="form-control" placeholder="example@gmail.com" name="email" tabindex="9" value="<?=$form->email?>">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-4 control-label">Вид інвалідності:</label>
                    <div class="col-sm-8">
                        <div class="input-group">
                            <select name="id_vud_inval" class="form-control" tabindex="10" >
                                <?php foreach ($vud_invals as $vud_inval): ?>
                                    <option value="<?=$vud_inval['id']?>">
                                        <?=$vud_inval['vud']?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                            <span class="input-group-btn">
                                <button class="btn btn-primary" type="button"><i class="fa fa-plus" aria-hidden="true"></i> Додати вид інвалідності</button>
                            </span>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-4 control-label">Група інвалідності:</label>
                    <div class="col-sm-8">
                        <select name="grup" class="form-control" tabindex="11" >
                            <option value="Без інвалідності">
                                Без інвалідності
                            </option>
                            <option value="І А - група">
                                І А - група
                            </option>
                            <option value="І Б - група">
                                І Б - група
                            </option>
                            <option value="ІІ - група">
                                ІІ - група
                            </option>
                            <option value="ІІІ - група">
                                ІІІ - група
                            </option>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-4 control-label">Дата звільнення з останнього місця роботи:</label>
                    <div class="col-sm-8">
                        <input type="date" class="form-control" name="freedate" tabindex="12" value="<?=$form->freedate?>">
                    </div>
                </div>
                
            </fieldset>
            <button class="btn btn-success btn-lg" type="submit"><i class="fa fa-plus-circle" aria-hidden="true"></i> Зберегти та продовжити</button>
            <a href="/thirdpage" class="btn btn-danger btn-lg" role="button"><i class="fa fa-ban" aria-hidden="true"></i> Відмінити</a>
        </form>
    </h4>
    </div>
</div>

<b id="flash"><?=\Library\Session::getFlash()?></b>