<div class="page-header">
    <h2>Змінити роботу що шукає</h2>
</div>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <form method="post" class="form-horizontal">
            <fieldset>
                <div class="form-group">
                    <label class="col-sm-4 control-label">Спеціальність:</label>
                    <div class="col-sm-8">
                        <input type="text" name="specialty" class="form-control" tabindex="1" autofocus value="<?=$oldjobsearch['specialty']?>">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-4 control-label">Графік роботи:</label>
                    <div class="col-sm-8">
                        <select name="job_grapf" class="form-control">
                            <option value="1" <?=($oldjobsearch['job_grapf']==1) ? "selected" : ""?>>
                                Повний робочий день
                            </option>
                            <option value="2" <?=($oldjobsearch['job_grapf']==2) ? "selected" : ""?>>
                                Скорочений робочий день
                            </option>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-4 control-label">Тип роботи:</label>
                    <div class="col-sm-8">
                        <select name="sort_job" class="form-control" tabindex="3">
                            <option value="1" <?=($oldjobsearch['sort_job']==1) ? "selected" : ""?>>
                                Основна
                            </option>
                            <option value="2" <?=($oldjobsearch['sort_job']==2) ? "selected" : ""?>>
                                Сумісництво
                            </option>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-4 control-label">Заробітня плата:</label>
                    <div class="col-sm-8">
                        <div class="input-group">
                            <input type="text" name="salary" class="form-control"  tabindex="4" placeholder="Очикуваний рівень заробітньої платні" value="<?=$oldjobsearch['salary']?>">
                            <div class="input-group-addon">грн.</div>
                        </div>
                    </div>
                </div>

            </fieldset>

            <p>
                <button class="btn btn-success btn-lg" type="submit"><i class="fa fa-floppy-o" aria-hidden="true"></i> Зберегти роботу</button>
                <a href="/showjobsearch/<?=$oldjobsearch['id_jobseekers']?>#serc" class="btn btn-danger btn-lg" role="button"><i class="fa fa-ban" aria-hidden="true"></i> Відмінити</a>
            </p>
        </form>
    </div>
</div>

<b id="flash"><?=\Library\Session::getFlash()?></b>

