
    <table  class="table table-responsive table-striped table-hover">
        <thead>
        <tr>
            <th><h3>Прізвище</h3></th>
            <th><h3>Ім'я</h3></th>
            <th><h3>По-батькові</h3></th>
            <th><h3>Контакти</h3></th>
            <th class="th-center"><h3>Дія</h3></th>
        </tr>
        </thead>
        <tbody>
        <?php if (!$seekerses==null){?>
        <?php foreach ($seekerses as $seekers): ?>
        <tr>
            <td class="td-left"><?=$seekers['surname']?></td>
            <td class="td-left"><?=$seekers['jobseekername']?></td>
            <td class="td-left"><?=$seekers['father']?></td>
            <td class="td-left"><?=$seekers['contact']?></td>
            <td><a href="/showjobsearch/<?= $seekers['id'] ?>" class="btn btn-info" role="button"><i class="fa fa-eye" aria-hidden="true"></i> Переглянути</a><br></td>
        </tr>
            <?php endforeach; }?>
        </tbody>
    </table>