<div class="page-header">
    <h2>Змінити інформацію про пророблену роботу</h2>
</div>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <form method="post" class="form-horizontal">
            <fieldset>
                <div class="form-group">
                    <label class="col-sm-4 control-label">Вид роботи:</label>
                    <div class="col-sm-8">
                        <select name="vuddialnosti" class="form-control" disabled>
                            <option value="<?=$oldmoremade['vuddialnosti']?>">
                                <?=$oldmoremade['vuddialnosti']?>
                            </option>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-4 control-label">Результат:</label>
                    <div class="col-sm-8">
                        <input type="text"  name="made" class="form-control" tabindex="1" autofocus placeholder="" value="<?=$oldmoremade['made']?>">
                    </div>
                </div>
                <p>
                    <button class="btn btn-success btn-lg" type="submit"><i class="fa fa-floppy-o" aria-hidden="true"></i> Зберегти роботу</button>
                    <a href="/showjobsearch/<?=$oldmoremade['id_jobseekers']?>#serc" class="btn btn-danger btn-lg" role="button"><i class="fa fa-ban" aria-hidden="true"></i> Відмінити</a>
                </p>
            </fieldset>
        </form>

    </div>
</div>

<b id="flash"><?=\Library\Session::getFlash()?></b>