<div class="page-header">
    <h2>Змінити попередні звернення шукача роботи</h2>
</div>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <form method="post" class="form-horizontal">
            <fieldset>
                <div class="form-group">
                    <label class="col-sm-4 control-label">Куди звертався:</label>
                    <div class="col-sm-8">
                        <input type="text" name="organization" class="form-control" placeholder="Назва організації" value="<?=$oldpastresort['organization']?>">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-4 control-label">Дата звернення:</label>
                    <div class="col-sm-8">
                        <input type="date" name="resort_date" class="form-control" value="<?=$oldpastresort['resort_date']?>">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-4 control-label">Посада:</label>
                    <div class="col-sm-8">
                        <input type="text" name="posada" class="form-control" value="<?=$oldpastresort['posada']?>">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-4 control-label">Результат:</label>
                    <div class="col-sm-8">
                        <input type="text" name="result" class="form-control" value="<?=$oldpastresort['result']?>">
                    </div>
                </div>

            </fieldset>
            <p>
                <button class="btn btn-success btn-lg" type="submit"><i class="fa fa-floppy-o" aria-hidden="true"></i> Зберегти звернення</button>
                <a href="/showjobsearch/<?=$oldpastresort['id_jobseekers']?>#prevapl" class="btn btn-danger btn-lg" role="button"><i class="fa fa-ban" aria-hidden="true"></i> Відмінити</a>
            </p>
        </form>
    </div>
</div>

<b id="flash"><?=\Library\Session::getFlash()?></b>