
<div class="page-header">
    <h2>Додати попередні звернення шукача роботи</h2>
</div>
<div class="row">
    <div class="col-md-3">
        <button id="showresort01" class="btn btn-primary btn-block"><i class="fa fa-university fa-1x" aria-hidden="true"></i> Місцеві органи державної влади</button>
    </div>
    <div class="col-md-3">
        <button id="showresort02" class="btn btn-primary btn-block"><i class="fa fa-archive fa-1x" aria-hidden="true"></i> Центри зайнятості</button>
    </div>
    <div class="col-md-3">
        <button id="showresort03" class="btn btn-primary btn-block"><i class="fa fa-users fa-1x" aria-hidden="true"></i> Громадські об'єднання</button>
    </div>
    <div class="col-md-3">
        <button id="showresort04" class="btn btn-primary btn-block"><i class="fa fa-industry fa-1x" aria-hidden="true"></i> Приватний бізнес</button>
    </div>
</div>
<br><br>
<div class="row" id="formpastresortcreate">
    <div class="col-md-6 col-md-offset-3">
        <form method="post" class="form-horizontal">
            <fieldset>
                <div class="form-group">
                    <label class="col-sm-4 control-label">Куди звертався:</label>
                    <div class="col-sm-8">
                        <input type="text" name="organization" class="form-control" placeholder="Назва організації" value="<?=$form->organization?>">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-4 control-label">Дата звернення:</label>
                    <div class="col-sm-8">
                        <input type="date" name="resort_date" class="form-control" value="<?=$form->resort_date?>">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-4 control-label">Посада:</label>
                    <div class="col-sm-8">
                        <input type="text" name="posada" class="form-control" value="<?=$form->posada?>">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-4 control-label">Результат:</label>
                    <div class="col-sm-8">
                        <input type="text" name="result" class="form-control" value="<?=$form->result?>">
                    </div>
                </div>

            </fieldset>
            <p>
                <button class="btn btn-success btn-lg" type="submit"><i class="fa fa-plus-circle" aria-hidden="true"></i> Додати звернення</button>
                <a href="/showjobsearch/<?=$form->id_jobseekers?>#prevapl" class="btn btn-danger btn-lg" role="button"><i class="fa fa-ban" aria-hidden="true"></i> Відмінити</a>
            </p>
        </form>
    </div>
</div>

<script>
    $('#formpastresortcreate').hide();
</script>
<b id="flash"><?=\Library\Session::getFlash()?></b>