<div class="page-header">
    <h2>Повторно звернувся</h2>
</div>
<form method="post"  class="form-horizontal">
    <fieldset>
        <div class="form-group">
            <label class="col-md-4 control-label">Коментар:</label>
            <div class="col-md-8">
                <input type="text" name="made" class="form-control" tabindex="1" autofocus value="<?=$form->made?>">
            </div>
        </div>
    </fieldset>
    <button class="btn btn-success btn-lg" type="submit"><i class="fa fa-plus-circle" aria-hidden="true"></i> Повторно звернувся</button>
    <a href="/showjobsearch/<?=$form->id_jobseekers?>" class="btn btn-danger btn-lg" role="button"><i class="fa fa-ban" aria-hidden="true"></i> Відмінити</a>
</form>

<b id="flash"><?=\Library\Session::getFlash()?></b>


