<div class="page-header">
    <h2>
        <?php
        switch ($vud) {
            case 1:
                echo "Місцеві органи державної влади";
                break;
            case 2:
                echo "Центри зайнятості";
                break;
            case 3:
                echo "Громадські об'єднання";
                break;
            case 4:
                echo "Приватний бізнес";
                break;
            default:
                echo "";
        }
        ?>
    </h2>

</div>

<div class="row">
    <div class="col-md-4">
        <input id="search" type="text"  class="form-control" name="search" placeholder="Введіть назву організації для пошуку">
    </div>
    <div class="col-md-4">
        <a id="botn" class="btn btn-success btn-md" role="button"><i class="fa fa-search" aria-hidden="true"></i> ЗНАЙТИ</a>
        <a class="btn btn-danger btn-md  text-uppercase" href="/showallcompany/<?= $vud ?>" role="button"><i class="fa fa-times-circle" aria-hidden="true"></i> Показати всі організації</a>
    </div>
    <div class="col-md-4">
        <a class="btn btn-primary btn-md  text-uppercase" href="/companycreate/<?= $vud ?>" role="button"><i class="fa fa-plus" aria-hidden="true"></i> Додати нову організацію</a>
    </div>
</div>

    <script>
        $(document).ready(function() {

            $('#botn').click(function () {
                var searchValue = $('#search').val();
//                alert(searchValue);
                $.post('/onecompany', {search: searchValue}).done(function(data) {
                    $("#tyt").html(data);
                });
            });
        });
    </script>

<br>
<div id="tyt">
    <table class="table table-responsive table-striped table-hover">
        <thead>
            <tr>
                <th><h3>Компанія</h3></th>
                <th><h3>Контакти</h3></th>
                <th  class="th-center"><h3>Дія</h3></th>
                <!--            <td class="active"><h3>E-mail</h3></td>-->
            </tr>
        </thead>
    <tbody>
        <?php if (!$companes==null){?>
        <?php foreach ($companes as $company): ?>

        <tr>
            <td class="td-left"><?=$company['company']?></td>
            <td class="td-left"><?=$company['contact']?></td>
            <td><a href="/showcompany/<?= $company['id'] ?>" class="btn btn-info" role="button"><i class="fa fa-eye" aria-hidden="true"></i> Переглянути</a><br></td>

<!--            <td><a href="/showuser/--><?//= $company['id'] ?><!--" class="btn btn-info" role="button"><i class="fa fa-search" aria-hidden="true"></i> Переглянути</a><br></td>-->
        </tr>
            <?php endforeach; }?>
    </tbody>
    </table>
</div>