<div class="stilozvit">
    1. Кількість осіб, що звернулись до центру: <?=$zvernen?> осіб:
    <div class="stiloznachzvit">- з них жінок: <?=$zvernenwoman?>;</div>
    <div class="stiloznachzvit">- з них чоловіків: <?=$zvernenman?>;</div>
</div>
<div class="stilozvit">
    2. З них мають інвалідність: *знач* осіб:
    <?php foreach ($grupuinval as $grupinval): ?>
        <div class="stiloznachzvit">- з них <?=$grupinval['grup']?>: <?=$grupinval['COUNT(*)']?> осіб;</div>
    <?php endforeach;?>

    <div class="stiloznachzvit">- з них кожного виду інвалідності: *знач*;</div>
</div>
<div class="stilozvit">
    3. Результат проведенної роботи:
    <div class="stiloznachzvit">- працевлаштовано <?=$rezultat['pynkt_tru_odun']?> осіб;</div>
    <div class="stiloznachzvit">- надано допомоги у працевлаштуванні <?=$rezultat['pynkt_tru_dva']?> особам;</div>
    <div class="stiloznachzvit">- надання допомоги з оформлення документів <?=$rezultat['pynkt_tru_tru']?> особам;</div>
    <div class="stiloznachzvit">- ведеться робота з пошуку робочого місця для <?=$statuswork?> осіб;</div>
    <div class="stiloznachzvit">- відмовлено у наданні допомоги <?=$rezultat['pynkt_tru_piat']?> особам;</div>
    <div class="stiloznachzvit">- надано <?=$rezultat['pynkt_tru_shist']?> консультацій</div>
</div>
<div class="stilozvit">
    4. Направлено ... (звернутися) до:
    <div class="stiloznachzvit">- місцевих органів державної влади <?=$choturu['pynkt_choturu_odun']?> осіб;</div>
    <div class="stiloznachzvit">- центрів зайнятості <?=$choturu['pynkt_choturu_dva']?> осіб;</div>
    <div class="stiloznachzvit">- громадських організацій <?=$choturu['pynkt_choturu_tru']?> осіб;</div>
    <div class="stiloznachzvit">- приватних роботодавців <?=$choturu['pynkt_choturu_choturu']?> осіб;</div>
</div>
<div class="stilozvit">
    5. Соціальний супровід проводиться з <?=$rezultat['pynkt_piat']?> клієнтами.
</div>
</div>
<br><br><br><br><br>
<div class="row">
    <a href="" class="thumbnail">
        <h6>
            <i class="fa fa-file-pdf-o fa-3x" aria-hidden="true"> Сформувати PDF файл</i>
        </h6>
    </a>
</div>