<div class="row">
    <h6>
        <a href="/showallcompany/<?=$company['vud']?>" class="thumbnail">
            <i class="fa fa-arrow-left fa-2x" aria-hidden="true"> Повернутися до списку організацій</i>
        </a>
    </h6>
</div>
<div class="page-header">
    <h1 class="text-uppercase"><strong>Організація</strong> <small><?=$company['company']?></small></h1>
</div>
<div class="row">
    <div class="col-md-8 text-left">
        <h3>
            <div class="row svalueanketa">
                Назва організації(установи): <span class="slabelanketa"><?=$company['company']?></span><br>
                ПІБ керівника: <span class="slabelanketa"><?= $company['PIB'] ?></span><br>
                Номер телефону: <span class="slabelanketa"><?= $company['telefon'] ?></span><br>
                Контакти: <span class="slabelanketa"><?= $company['contact'] ?></span><br>
                E-mail: <span class="slabelanketa"><?= $company['email'] ?></span><br>
                <br>
            </div>
        </h3>
    </div>
    <div class="col-md-4  text-right">
        <div class=" col-md-offset-5 col-md-7"><a href="/updatecompany/<?= $company['id'] ?>" class="btn btn-success btn-block" role="button"><i class="fa fa-pencil" aria-hidden="true"></i> Редагувати</a><br></div>
        <!--<div class="text-right"><a  class="btn btn-warning" role="button">Працевлаштовано</a>-->
        <div class=" col-md-offset-5 col-md-7"><a href="#" class="btn btn-danger btn-block company<?=$company['id']?>" role="button"><i class="fa fa-trash" aria-hidden="true"></i> Видалити</a></div>
        <!--        </div>-->
    </div>
</div>
<script>
    $('.company<?=$company['id']?>').click(function() {
        $.get('/deletecompany/<?=$company['id']?>');
        window.location = "/thirdpage";
    });
</script>