

<a href="/userupdate/<?= $user['id'] ?>" class="btn btn-primary" role="button"><b>Змінити дані працівника</b></a><br><br>
<h3>
Прізвище:<b><?= $user['surname'] ?></b><br>
Ім'я:<b><?= $user['username'] ?></b><br>
По-батькові:<b><?= $user['father'] ?></b><br>
Регіон:<b><?= $user['id_region'] ?></b><br>
Працює з:<b><?= $user['startwork'] ?></b><br>
Контакти:<b><?= $user['contact'] ?></b><br>

Статус:<b><?php if ($user['status']==1){echo 'адміністратор';}
elseif ($user['status']==2){echo 'керівник регіону';}
else{echo 'користувач';}?></b><br>
E-mail:<b><?= $user['email'] ?></b><br>
</h3>
<?php if (isset($user['foto'])){echo '<img src="data:image/jpeg;base64,'.base64_encode($user['foto']).'" />';};?>
