<br><br><br>
<div class="row">
    <div class="col-xs-6 col-md-6">
        <div class="w100 thumbnail hvr-fade">
            <a href="/jobseekercreate" class="hw">
                <p>
                    <i class="fa fa-user-plus fa-5x" aria-hidden="true"></i>
                </p>
                <p>
                    <h3>Анкета нового шукача роботи</h3>
                </p>
            </a>
        </div>
    </div>

    <div class="col-xs-6 col-md-6">
        <div class="w100 thumbnail hvr-fade">
            <a href="/alljobseekeres">
                <p>
                    <i class="fa fa-user fa-5x" aria-hidden="true"></i>
                </p>
                <p>
                <h3>Переглянути анкети шукачів роботи</h3>
                </p>
            </a>
        </div>
    </div>
</div>


<br><br>
<hr class="coloris">
<br><br><br>


<div class="row">
    <div class="col-xs-6 col-md-3">
        <div class='stackone sblue'>
            <a href="/showallcompany/1" >
                <p>
                    <i class="fa fa-university fa-5x" aria-hidden="true"></i>
                </p>
                <p>
                <h3>Місцеві органи державної влади</h3>
                </p>
            </a>
        </div>
    </div>
    <div class="col-xs-6 col-md-3">
        <div class='stackone sgreen'>
            <a href="/showallcompany/2">
                <p>
                    <i class="fa fa-archive fa-5x" aria-hidden="true"></i>
                </p>
                <p>
                    <h3>Центри <p>зайнятості</p></h3>
                </p>
            </a>
        </div>
    </div>
    <div class="col-xs-6 col-md-3">
        <div class='stackone sorange'>
            <a href="/showallcompany/3">
                <p>
                    <i class="fa fa-users fa-5x" aria-hidden="true"></i>
                </p>
                <p>
                <h3>Громадські об'єднання</h3>
                </p>
            </a>
        </div>
    </div>
    <div class="col-xs-6 col-md-3">
        <div class='stackone spurple'>
            <a href="/showallcompany/4">
                <p>
                    <i class="fa fa-industry fa-5x" aria-hidden="true"></i>
                </p>
                <p>
                <h3>Приватний <p>бізнес</p></h3>
                </p>
            </a>
        </div>
    </div>
</div>
