<div class="page-header">
    <h2>Редагувати організацію</h2>
</div>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <form method="post" class="form-horizontal">
            <fieldset>
                <div class="form-group">
                    <label class="col-md-4 control-label">Назва організації:</label>
                    <div class="col-md-8">
                        <input type="text" name="company" class="form-control" value="<?=$oldcompany['company']?>">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-4 control-label">ПІБ керівника:</label>
                    <div class="col-md-8">
                        <input type="text" name="PIB" class="form-control" value="<?=$oldcompany['PIB']?>">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-4 control-label">Контакти:</label>
                    <div class="col-md-8">
                        <textarea name="contact" rows="7" class="form-control"><?=$oldcompany['contact']?></textarea>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-4 control-label">Телефон:</label>
                    <div class="col-md-8">
                        <div class="input-group">
                            <div class="input-group-addon">+38</div>
                            <input type="text" name="telefon" class="form-control" value="<?=$oldcompany['telefon']?>">
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-4 control-label">E-mail:</label>
                    <div class="col-md-8">
                        <input type="email" name="email" class="form-control" value="<?=$oldcompany['email']?>">
                    </div>
                </div>

            </fieldset>
            <button class="btn btn-success btn-lg" type="submit"><i class="fa fa-floppy-o" aria-hidden="true"></i> Зберегти організацію</button>
            <a href="/showcompany/<?=$oldcompany['id']?>" class="btn btn-danger btn-lg" role="button"><i class="fa fa-ban" aria-hidden="true"></i> Відмінити</a>
        </form>
    </div>
</div>

<b id="flash"><?=\Library\Session::getFlash()?></b>