<div class="row">
    <h1 class="stitzvit">Узагальнений звіт про результати роботи центру
        працевлаштування громадян <?=$reg['region']?> осередку ГОІ "ВАПІ" за ІІ квартал 2016 року<br><br></h1>

    <h4><br>
        <form>
            <label> Звіт за
                <select id="search" name="search">
                    <option value="1">
                        І-квартал
                    </option>
                    <option value="2">
                        ІІ-квартал
                    </option>
                    <option value="3">
                        ІІІ-квартал
                    </option>
                    <option value="4">
                        IV-квартал
                    </option>
                </select>
            </label>
            <label>
                <select id="year" name="year">
                    <option value="2016">
                        2016 року
                    </option>
                    <option value="2017">
                        2017 року
                    </option>
                    <option value="2018">
                        2018 року
                    </option>
                    <option value="2019">
                        2019 року
                    </option>
                </select>
            </label>
            <a id="botn" class="btn btn-danger btn-md" role="button"><i class="fa fa-ban" aria-hidden="true"></i>ЗМІНИТИ</a>
        </form>
        <script>
            $(document).ready(function() {

                $('#botn').click(function () {
                    var searchValue = $('#search').val();
                    var yearValue = $('#year').val();
//                    alert(searchValue);
                    alert(searchValue + yearValue);
                    $.post('/showzvit', {search: searchValue, year: yearValue}).done(function(data) {
                        $("#tyt").html(data);
                    });
                });
            });
        </script>
    </h4>

    <div id="tyt"></div>

















    